# Generated by Django 5.2.3 on 2025-07-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_image", models.ImageField(upload_to="products/")),
                ("category", models.CharField(max_length=90)),
                ("product_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
